apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "chart.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "chart.fullname" . }}-serving-cert
  labels:
  {{- include "chart.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-garm-operator-mercedes-benz-com-v1alpha1-image
  failurePolicy: Fail
  name: validate.image.garm-operator.mercedes-benz.com
  rules:
  - apiGroups:
    - garm-operator.mercedes-benz.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - images
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-garm-operator-mercedes-benz-com-v1alpha1-pool
  failurePolicy: Fail
  name: validate.pool.garm-operator.mercedes-benz.com
  rules:
  - apiGroups:
    - garm-operator.mercedes-benz.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-garm-operator-mercedes-benz-com-v1alpha1-repository
  failurePolicy: Fail
  name: validate.repository.garm-operator.mercedes-benz.com
  rules:
  - apiGroups:
    - garm-operator.mercedes-benz.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None