apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Image
metadata:
  labels:
    app.kubernetes.io/name: image
    app.kubernetes.io/instance: image-sample
    app.kubernetes.io/part-of: garm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: garm-operator
  name: runner-default
  namespace: garm-operator-system
spec:
  tag: runner:linux-ubuntu-22.04-arm64
---
apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Organization
metadata:
  labels:
    app.kubernetes.io/name: organization
    app.kubernetes.io/instance: organization-sample
    app.kubernetes.io/part-of: garm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: garm-operator
  name: github-actions
  namespace: garm-operator-system
spec:
  webhookSecretRef:
    key: "webhookSecret"
    name: "org-webhook-secret"
  credentialsName: "github-pat"
---
apiVersion: v1
kind: Secret
metadata:
  name: org-webhook-secret
  namespace: garm-operator-system
data:
  webhookSecret: bXlzZWNyZXQ=
---
apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Pool
metadata:
  name: kubernetes-pool-medium-org-github-actions
  namespace: garm-operator-system
spec:
  githubScopeRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: Organization
    name: github-actions
  enabled: true
  flavor: medium
  extraSpecs: '{}'
  githubRunnerGroup: ""
  imageName: runner-default
  maxRunners: 2
  minIdleRunners: 1
  osArch: arm64
  osType: linux
  providerName: kubernetes_external
  runnerBootstrapTimeout: 2
  runnerPrefix: "road-runner-k8s-rthalho"
  tags:
    - medium
    - k8s-dev
    - garm-operator-dev
